image: rambabusaravanan/firebase

stages:
  - deploy

cache:                  
  paths:                
    - node_modules/     
  key: "$CI_BUILD_REPO" 

deploy-prod:
  stage: deploy
  only:
    - master
  script:
    - yarn
    - yarn run build
    - firebase use project-id: ${{ secrets.project-id}} --token FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    - firebase deploy --only hosting -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID" --token FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
