name: Firebase Deploy

on:
  push:
    braches: 
      - master

jobs:
  firebase:
    name: Build and Deploy Firebase Hosting
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn
      - name: Build vue contents
        run: yarn build
      - name: Deploy to Firebase
        uses: git@github.com:My-pen/LadyBirds.git
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
